### ISSUE TITLE
Additional arguments in console.* methods are added to the source

### ISSUE THREAD

**Issue by btakita** [gijsk/remove-console-logs#4]
``` javascript
console.log('modal/modal|ModalInstance#close|main', index, queue.length, queue[0] && queue[0].$el.attr("id"));
```

Leaves behind:

``` javascript
(queue[0].$el.attr("id") && 0);
```

**Comment by gijsk** [comment]
Wow, almost 3 years. It's probably not a record because, well, the world and github. But I just went and fixed this. I also added an option that removes all arguments (even if they might have side effects), and updated the code so stand-alone console.log statements are removed altogether.
